name: Campaign Expiration Email Notification

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-campaigns:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Use a newer version
    
    - name: Check Campaign Dates
      id: check-campaigns
      run: |
        echo "Checking campaign expiration..."
        node <<EOF
        const fs = require('fs');
        const path = require('path');

        // Read campaign.json
        const campaignData = JSON.parse(fs.readFileSync('campaign.json', 'utf8'));
        const today = new Date();
        const twoWeeks = 14 * 24 * 60 * 60 * 1000;

        // Check for expiring campaigns
        const expiringCampaigns = campaignData.filter(campaign => {
          if (campaign.status !== 'Active') return false;
          const endDate = new Date(campaign.endDate);
          return endDate.getTime() - today.getTime() <= twoWeeks && endDate.getTime() > today.getTime();
        });

        if (expiringCampaigns.length > 0) {
          const emailBody = expiringCampaigns.map(c => 
            `- ${c.campaignName}: ${Math.ceil((new Date(c.endDate) - today) / (1000 * 60 * 60 * 24))} days left (End date: ${c.endDate})`
          ).join('\n');

          console.log("Expiring Campaigns Found:");
          console.log(emailBody);
          fs.writeFileSync('email_body.txt', emailBody);
        } else {
          console.log("No campaigns expiring soon.");
        }
        EOF

    - name: Send Email if Needed
      if: success()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.sookarespond@gmail.com }}
        password: ${{ secrets.sooka123456 }}
        subject: "Campaign Expiration Reminder"
        body_file: "email_body.txt"
        to: "kohch7811@gmail.com"
        from: "GitHub Actions"

