name: Campaign Expiration Email Notification

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-campaigns:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Generate Email Body
      run: |
        node <<EOF
        const fs = require('fs');

        const campaignData = JSON.parse(fs.readFileSync('campaign.json', 'utf8'));
        const today = new Date();
        const twoWeeks = 14 * 24 * 60 * 60 * 1000;

        const expiringCampaigns = campaignData.filter(campaign => {
          if (campaign.status !== 'Active') return false;
          const endDate = new Date(campaign.endDate);
          return endDate.getTime() - today.getTime() <= twoWeeks && endDate.getTime() > today.getTime();
        });

        if (expiringCampaigns.length > 0) {
          let emailBody = `📢 [Campaign Expiration Reminder] 📢\n\n`;
          emailBody += `The following campaigns are about to expire. Please take action:\n\n`;
          emailBody += `------------------------------------------------\n`;
          emailBody += `📅 End Date        | 📌 Campaign Name\n`;
          emailBody += `------------------------------------------------\n`;

          expiringCampaigns.forEach(campaign => {
            const endDate = new Date(campaign.endDate).toISOString().split('T')[0];
            emailBody += `${endDate}       | ${campaign.campaignName}\n`;
          });

          emailBody += `------------------------------------------------\n\n`;
          emailBody += `⚠️ Please review and decide whether to extend or take necessary actions.\n\n`;
          emailBody += `🔗 GitHub Repository: https://github.com/${{ github.repository }}\n\n`;
          emailBody += `This is an automated notification from GitHub Actions. Please do not reply.`;

          fs.writeFileSync('email_body.txt', emailBody);
        } else {
          console.log("No campaigns are expiring soon.");
        }
        EOF

    - name: Send Email Notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Campaign Expiration Reminder"
        body_file: "email_body.txt"
        to: "kohch7811@gmail.com"
        from: "GitHub Actions"
